package service.corbaBanque;


/**
* corbaBanque/IBanqueRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* samedi 15 novembre 2025 12 h 59 WAT
*/

public interface IBanqueRemote extends IBanqueRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface IBanqueRemote
