package service.corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* samedi 15 novembre 2025 12 h 59 WAT
*/

public interface IBanqueRemoteOperations 
{
  void creerCompte (Compte cpte);
  void verser (float mt, int code);
  void retirer (float mt, int code);
  Compte getCompte (int code);
  Compte[] getComptes ();
  float conversion (float mt);
} // interface IBanqueRemoteOperations
