package service.corbaBanque;

/**
* corbaBanque/IBanqueRemoteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Banque.idl
* samedi 15 novembre 2025 12 h 59 WAT
*/

public final class IBanqueRemoteHolder implements org.omg.CORBA.portable.Streamable
{
  public IBanqueRemote value = null;

  public IBanqueRemoteHolder ()
  {
  }

  public IBanqueRemoteHolder (IBanqueRemote initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IBanqueRemoteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IBanqueRemoteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IBanqueRemoteHelper.type ();
  }

}
